--- # first task file
- hosts: demo
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: installing httpd
      package:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: enable httpd
      ansible.builtin.service:
        name: httpd
        enabled: yes


